<?php $titre = 'Home'; ?>

<?php ob_start(); ?>

<div>
    <img class="img-fluid" src="assets/images/berserkTreeResize.png">
</div>

<div class="contentSpacing">
    
    <h1 class="text-center mb-5"> MyList </h1>

    <div class="">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mattis nunc sed blandit libero volutpat sed cras. In ornare quam viverra orci sagittis eu volutpat. Massa placerat duis ultricies lacus sed turpis tincidunt id. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Nunc pulvinar sapien et ligula. Aliquam eleifend mi in nulla posuere. Egestas dui id ornare arcu odio ut sem nulla pharetra. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Id venenatis a condimentum vitae sapien pellentesque habitant. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla.
            Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Tincidunt nunc pulvinar sapien et. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Senectus et netus et malesuada fames. Arcu risus quis varius quam quisque id diam vel. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Eget nullam non nisi est sit amet. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Malesuada proin libero nunc consequat interdum varius sit amet. Ut tortor pretium viverra suspendisse. Sodales ut etiam sit amet nisl. A scelerisque purus semper eget duis. Sagittis purus sit amet volutpat consequat mauris nunc. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Faucibus et molestie ac feugiat sed lectus. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Lectus sit amet est placerat.
        </p>
        <p>
            Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Tempor id eu nisl nunc mi ipsum. Vel risus commodo viverra maecenas accumsan. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Aliquam sem fringilla ut morbi tincidunt augue interdum. Habitant morbi tristique senectus et netus et malesuada. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Amet consectetur adipiscing elit ut aliquam purus. Condimentum lacinia quis vel eros donec ac. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Et tortor at risus viverra adipiscing at in tellus. Et pharetra pharetra massa massa ultricies mi quis. A arcu cursus vitae congue mauris rhoncus aenean vel. Urna molestie at elementum eu. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Condimentum lacinia quis vel eros donec ac odio tempor orci.
            Enim neque volutpat ac tincidunt vitae. Nibh cras pulvinar mattis nunc sed blandit. Ipsum faucibus vitae aliquet nec ullamcorper. Adipiscing enim eu turpis egestas pretium aenean pharetra. Turpis egestas sed tempus urna et pharetra pharetra massa. Egestas purus viverra accumsan in nisl. Euismod in pellentesque massa placerat duis ultricies lacus. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Enim ut tellus elementum sagittis vitae et leo duis ut. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Sem fringilla ut morbi tincidunt augue interdum velit euismod.
        </p>
        <p>
            Arcu ac tortor dignissim convallis aenean et tortor at risus. Sed enim ut sem viverra aliquet eget sit amet. Interdum velit euismod in pellentesque massa placerat. Fermentum dui faucibus in ornare quam viverra orci sagittis. Sit amet cursus sit amet. Nibh nisl condimentum id venenatis a condimentum vitae. Dui sapien eget mi proin sed libero enim sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor condimentum lacinia quis vel eros. Molestie nunc non blandit massa enim nec dui. Consectetur adipiscing elit pellentesque habitant morbi tristique. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Vitae turpis massa sed elementum tempus egestas sed sed risus. Consequat ac felis donec et. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Mauris a diam maecenas sed enim. Leo vel fringilla est ullamcorper.   
            Quisque non tellus orci ac auctor. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Sapien et ligula ullamcorper malesuada proin. Nam libero justo laoreet sit amet cursus sit. Et netus et malesuada fames ac turpis egestas. Pellentesque elit eget gravida cum sociis natoque penatibus. Suspendisse interdum consectetur libero id faucibus nisl. Ut tristique et egestas quis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Id porta nibh venenatis cras sed felis eget velit aliquet.
        </p>
        <p>
            Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Tempor id eu nisl nunc mi ipsum. Vel risus commodo viverra maecenas accumsan. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Aliquam sem fringilla ut morbi tincidunt augue interdum. Habitant morbi tristique senectus et netus et malesuada. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Amet consectetur adipiscing elit ut aliquam purus. Condimentum lacinia quis vel eros donec ac. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Et tortor at risus viverra adipiscing at in tellus. Et pharetra pharetra massa massa ultricies mi quis. A arcu cursus vitae congue mauris rhoncus aenean vel. Urna molestie at elementum eu. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Condimentum lacinia quis vel eros donec ac odio tempor orci.
            Enim neque volutpat ac tincidunt vitae. Nibh cras pulvinar mattis nunc sed blandit. Ipsum faucibus vitae aliquet nec ullamcorper. Adipiscing enim eu turpis egestas pretium aenean pharetra. Turpis egestas sed tempus urna et pharetra pharetra massa. Egestas purus viverra accumsan in nisl. Euismod in pellentesque massa placerat duis ultricies lacus. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Enim ut tellus elementum sagittis vitae et leo duis ut. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Sem fringilla ut morbi tincidunt augue interdum velit euismod.
        </p>
        <p>
            Arcu ac tortor dignissim convallis aenean et tortor at risus. Sed enim ut sem viverra aliquet eget sit amet. Interdum velit euismod in pellentesque massa placerat. Fermentum dui faucibus in ornare quam viverra orci sagittis. Sit amet cursus sit amet. Nibh nisl condimentum id venenatis a condimentum vitae. Dui sapien eget mi proin sed libero enim sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor condimentum lacinia quis vel eros. Molestie nunc non blandit massa enim nec dui. Consectetur adipiscing elit pellentesque habitant morbi tristique. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Vitae turpis massa sed elementum tempus egestas sed sed risus. Consequat ac felis donec et. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Mauris a diam maecenas sed enim. Leo vel fringilla est ullamcorper.   
            Quisque non tellus orci ac auctor. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Sapien et ligula ullamcorper malesuada proin. Nam libero justo laoreet sit amet cursus sit. Et netus et malesuada fames ac turpis egestas. Pellentesque elit eget gravida cum sociis natoque penatibus. Suspendisse interdum consectetur libero id faucibus nisl. Ut tristique et egestas quis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Id porta nibh venenatis cras sed felis eget velit aliquet.
        </p>
        <p>
            Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Tempor id eu nisl nunc mi ipsum. Vel risus commodo viverra maecenas accumsan. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Aliquam sem fringilla ut morbi tincidunt augue interdum. Habitant morbi tristique senectus et netus et malesuada. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Amet consectetur adipiscing elit ut aliquam purus. Condimentum lacinia quis vel eros donec ac. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Et tortor at risus viverra adipiscing at in tellus. Et pharetra pharetra massa massa ultricies mi quis. A arcu cursus vitae congue mauris rhoncus aenean vel. Urna molestie at elementum eu. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Condimentum lacinia quis vel eros donec ac odio tempor orci.
            Enim neque volutpat ac tincidunt vitae. Nibh cras pulvinar mattis nunc sed blandit. Ipsum faucibus vitae aliquet nec ullamcorper. Adipiscing enim eu turpis egestas pretium aenean pharetra. Turpis egestas sed tempus urna et pharetra pharetra massa. Egestas purus viverra accumsan in nisl. Euismod in pellentesque massa placerat duis ultricies lacus. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Enim ut tellus elementum sagittis vitae et leo duis ut. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Sem fringilla ut morbi tincidunt augue interdum velit euismod.
        </p>
        <p>
            Arcu ac tortor dignissim convallis aenean et tortor at risus. Sed enim ut sem viverra aliquet eget sit amet. Interdum velit euismod in pellentesque massa placerat. Fermentum dui faucibus in ornare quam viverra orci sagittis. Sit amet cursus sit amet. Nibh nisl condimentum id venenatis a condimentum vitae. Dui sapien eget mi proin sed libero enim sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor condimentum lacinia quis vel eros. Molestie nunc non blandit massa enim nec dui. Consectetur adipiscing elit pellentesque habitant morbi tristique. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Vitae turpis massa sed elementum tempus egestas sed sed risus. Consequat ac felis donec et. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Mauris a diam maecenas sed enim. Leo vel fringilla est ullamcorper.   
            Quisque non tellus orci ac auctor. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Sapien et ligula ullamcorper malesuada proin. Nam libero justo laoreet sit amet cursus sit. Et netus et malesuada fames ac turpis egestas. Pellentesque elit eget gravida cum sociis natoque penatibus. Suspendisse interdum consectetur libero id faucibus nisl. Ut tristique et egestas quis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Id porta nibh venenatis cras sed felis eget velit aliquet.
        </p>
        <p>
            Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Tempor id eu nisl nunc mi ipsum. Vel risus commodo viverra maecenas accumsan. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Aliquam sem fringilla ut morbi tincidunt augue interdum. Habitant morbi tristique senectus et netus et malesuada. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Amet consectetur adipiscing elit ut aliquam purus. Condimentum lacinia quis vel eros donec ac. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Et tortor at risus viverra adipiscing at in tellus. Et pharetra pharetra massa massa ultricies mi quis. A arcu cursus vitae congue mauris rhoncus aenean vel. Urna molestie at elementum eu. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Condimentum lacinia quis vel eros donec ac odio tempor orci.
            Enim neque volutpat ac tincidunt vitae. Nibh cras pulvinar mattis nunc sed blandit. Ipsum faucibus vitae aliquet nec ullamcorper. Adipiscing enim eu turpis egestas pretium aenean pharetra. Turpis egestas sed tempus urna et pharetra pharetra massa. Egestas purus viverra accumsan in nisl. Euismod in pellentesque massa placerat duis ultricies lacus. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Enim ut tellus elementum sagittis vitae et leo duis ut. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Sem fringilla ut morbi tincidunt augue interdum velit euismod.
        </p>
        <p>
            Arcu ac tortor dignissim convallis aenean et tortor at risus. Sed enim ut sem viverra aliquet eget sit amet. Interdum velit euismod in pellentesque massa placerat. Fermentum dui faucibus in ornare quam viverra orci sagittis. Sit amet cursus sit amet. Nibh nisl condimentum id venenatis a condimentum vitae. Dui sapien eget mi proin sed libero enim sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor condimentum lacinia quis vel eros. Molestie nunc non blandit massa enim nec dui. Consectetur adipiscing elit pellentesque habitant morbi tristique. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Vitae turpis massa sed elementum tempus egestas sed sed risus. Consequat ac felis donec et. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Mauris a diam maecenas sed enim. Leo vel fringilla est ullamcorper.   
            Quisque non tellus orci ac auctor. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Sapien et ligula ullamcorper malesuada proin. Nam libero justo laoreet sit amet cursus sit. Et netus et malesuada fames ac turpis egestas. Pellentesque elit eget gravida cum sociis natoque penatibus. Suspendisse interdum consectetur libero id faucibus nisl. Ut tristique et egestas quis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Id porta nibh venenatis cras sed felis eget velit aliquet.
        </p>
    </div>
</div> 

<?php $contenu = ob_get_clean(); ?>

<?php require 'gabarit.php'; ?>